version: '3'
services:
  app:
    image: isubasinghe/pet-rego
    depends_on:
      - postgres
    environment:
      HOST: postgres
      USERNAME: postgres
      PASSWORD: password
      PORT: 5432
      DATABASE: postgres
    ports:
      - '3000:3000'

  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
